### ISSUE TITLE
Could this be used to modify properties of an already existing msi file?

### ISSUE THREAD

**Issue by slifin** [bonzini/msitools#2]
Hello, 
Apologise if this question seems naive, I'm looking for a solution where I can modify msi properties of an existing msi file in less than around 2 seconds so that I can send the modified msi file out to the client as part of a web page can that be accomplished with this tool on linux? If so where should I begin?

**Comment by madmod** [comment]
I am also interested in this. My current approach will likely be running the WiX toolset in a Docker container with Wine. I would prefer to not need this, as my use case is to add some customer specific info to the installer when they download it.

**Comment by bonzini** [comment]
You can use _msibuild file.msi -q "SQL-QUERY1" -q "SQL-QUERY2" ..._ to modify an existing MSI file.
